'use client';
import { useState, useCallback } from 'react';
import { ArrowRight, Check, Copy, FileText, Layers3, MessageSquare, Sparkles, Video } from 'lucide-react';
import ThinkingAnimation from '@/components/thinking/ThinkingAnimation';
const contentTypes = [
  { id: 'post', label: 'LinkedIn Post', icon: FileText, description: 'A clear founder-led post' },
  { id: 'carousel', label: 'Carousel', icon: Layers3, description: 'A structured multi-slide idea' },
  { id: 'thread', label: 'X Thread', icon: MessageSquare, description: 'A sequence with momentum' },
  { id: 'video', label: 'Video Script', icon: Video, description: 'A concise short-form script' },
];
export default function StudioPage() {
  const [selectedType, setSelectedType] = useState('post');
  const [prompt, setPrompt] = useState(() => { if (typeof window === 'undefined') return ''; const hook = sessionStorage.getItem('arbitrage_hook'); const angle = sessionStorage.getItem('arbitrage_angle'); sessionStorage.removeItem('arbitrage_hook'); sessionStorage.removeItem('arbitrage_angle'); return hook || angle ? `Use this hook: "${hook || ''}". ${angle ? `Strategy: ${angle}.` : ''}` : ''; });
  const [loading, setLoading] = useState(false); const [result, setResult] = useState(''); const [error, setError] = useState(''); const [copied, setCopied] = useState(false);
  const handleFirstToken = useCallback(() => undefined, []);
  const handleGenerate = async () => { if (!prompt.trim()) return; setLoading(true); setError(''); setResult(''); setCopied(false); try { const response = await fetch('/api/v1/studio/prompt', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ type: selectedType, user_input: prompt }) }); const data = await response.json(); if (data.success) setResult(data.data.content); else setError(data.error || 'Generation failed'); } catch { setError('Network error. Please try again.'); } finally { setLoading(false); } };
  const copyResult = async () => { await navigator.clipboard.writeText(result); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <div className="dm-route-page dm-studio-page"><div className="dm-page-title-row"><div><span className="dm-eyebrow">DeepMark Studio</span><h1>Make the next move legible.</h1><p>Give DeepMark a signal, a tension, or a rough idea. It will shape the first useful draft.</p></div><div className="dm-live-pill"><span /> Memory-aware generation</div></div><div className="dm-studio-grid"><section className="dm-route-card dm-studio-compose"><div className="dm-section-title"><span className="dm-route-empty-icon small"><Sparkles size={19} /></span><div><h2>What are we making?</h2><p>Choose a format, then describe the idea in your own words.</p></div></div><div className="dm-type-grid">{contentTypes.map((type) => { const Icon = type.icon; const active = selectedType === type.id; return <button key={type.id} className={`dm-type-card${active ? ' is-active' : ''}`} onClick={() => setSelectedType(type.id)}><Icon size={19} /><strong>{type.label}</strong><span>{type.description}</span>{active && <Check className="dm-type-check" size={15} />}</button>; })}</div><label className="dm-field-label" htmlFor="prompt">The raw signal</label><textarea id="prompt" className="dm-prompt-field" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="What happened, what changed, or what do you want your audience to understand?" /><div className="dm-compose-footer"><span>Write naturally. DeepMark will find the shape.</span><button className="dm-primary-button" onClick={handleGenerate} disabled={loading || !prompt.trim()}>{loading ? 'Thinking…' : 'Generate draft'} <ArrowRight size={15} /></button></div></section><aside className="dm-route-card dm-studio-side"><span className="dm-eyebrow">Signal quality</span><h2>Good inputs stay human.</h2><p>DeepMark works best when you bring the context only you have: the sharp opinion, the customer tension, or the change you are seeing.</p><div className="dm-signal-list"><div><span className="dm-signal-dot" /> A specific observation</div><div><span className="dm-signal-dot" /> A clear audience</div><div><span className="dm-signal-dot" /> One useful tension</div></div><div className="dm-side-rule" /><p className="dm-side-small">AI provider status is reported by the generation request. No content is shown as complete until the request returns.</p></aside></div>{loading && <div className="dm-thinking-panel"><ThinkingAnimation isActive={loading} onFirstToken={handleFirstToken} width={280} height={150} /></div>}{error && <div className="dm-error-banner">{error}</div>}{result && <section className="dm-route-card dm-result-card"><div className="dm-result-heading"><div><span className="dm-eyebrow">Draft ready</span><h2>Generated {contentTypes.find((type) => type.id === selectedType)?.label}</h2></div><button className="dm-copy-button" onClick={copyResult}>{copied ? <Check size={15} /> : <Copy size={15} />}{copied ? 'Copied' : 'Copy'}</button></div><div className="dm-result-body">{result}</div></section>}</div>;
}
