export default function TermsPage() {
  return (
    <article className="prose prose-invert max-w-none">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-[#999999] text-sm mb-8">Last updated: August 14, 2026</p>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">1. Acceptance of Terms</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            By accessing and using DeepMark ("the Service"), you accept and agree to be bound by the terms 
            and provision of this agreement. If you do not agree to abide by these terms, please do not 
            use this Service.
          </p>
          <p>
            These Terms of Service ("Terms") govern your use of DeepMark, an AI-powered marketing content 
            generation platform operated by DeepMark ("we," "us," or "our"). By using our Service, you 
            acknowledge that you have read, understood, and agree to be bound by these Terms.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">2. Description of Service</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            DeepMark provides an AI-powered platform for generating marketing content including but not 
            limited to social media posts, marketing threads, video scripts, content calendars, and 
            marketing strategies for startups and businesses.
          </p>
          <p>
            The Service includes various subscription tiers with different features, generations limits, 
            and pricing as displayed on our pricing page. By subscribing to our Service, you receive a 
            limited, non-exclusive, non-transferable license to use our platform for your internal 
            business purposes.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">3. User Obligations</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>By using DeepMark, you agree to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Provide accurate, current, and complete information during registration</li>
            <li>Maintain the security of your account credentials</li>
            <li>Notify us immediately of any unauthorized access to your account</li>
            <li>Not use the Service for any illegal or unauthorized purpose</li>
            <li>Not violate any laws in your jurisdiction while using the Service</li>
            <li>Not attempt to gain unauthorized access to any part of the Service</li>
            <li>Not interfere with or disrupt the Service or servers connected to the Service</li>
            <li>Not use automated tools to access the Service without our written permission</li>
            <li>Not resell, sublicense, or commercially exploit the Service without our consent</li>
          </ul>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">4. Intellectual Property</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            <strong className="text-[#FFFFFF]">Our Intellectual Property:</strong> The Service, including 
            all software, algorithms, designs, text, graphics, logos, and other content, is owned by 
            DeepMark and protected by intellectual property laws. You receive no ownership rights through 
            your use of the Service.
          </p>
          <p>
            <strong className="text-[#FFFFFF]">Your Content:</strong> You retain ownership of any content 
            you create, input, or upload to the Service ("User Content"). You grant us a limited license 
            to use your User Content solely to provide and improve the Service.
          </p>
          <p>
            <strong className="text-[#FFFFFF]">AI-Generated Content:</strong> Content generated by our 
            AI is provided for your use, but we make no claims of ownership over AI-generated outputs. 
            You are responsible for reviewing and ensuring the appropriateness of all content before 
            public use.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">5. Subscription and Payment</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            Subscription fees are billed in advance on a monthly or annual basis depending on your 
            selected plan. All fees are non-refundable except as required by law or at our sole discretion.
          </p>
          <p>
            You authorize us to charge your designated payment method for all fees associated with your 
            subscription. Failure to pay may result in suspension or termination of your account.
          </p>
          <p>
            We reserve the right to modify pricing at any time. Price changes will be communicated via 
            email at least 30 days before taking effect. Continued use of the Service after price 
            changes constitutes acceptance of the new pricing.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">6. Disclaimers</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER 
            EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>The Service will be uninterrupted, secure, or error-free</li>
            <li>The results obtained from using the Service will be accurate or reliable</li>
            <li>The quality of any content generated will meet your expectations</li>
            <li>Any errors in the Service will be corrected</li>
          </ul>
          <p>
            AI-generated content may contain inaccuracies, biases, or unintended outputs. You are solely 
            responsible for reviewing, editing, and verifying all AI-generated content before use.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">7. Limitation of Liability</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, DEEPMARK SHALL NOT BE LIABLE FOR ANY INDIRECT, 
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Loss of profits, revenue, data, or business opportunities</li>
            <li>Damages resulting from reliance on AI-generated content</li>
            <li>Costs of substitute goods or services</li>
            <li>Any damages arising from unauthorized access to your account</li>
          </ul>
          <p>
            OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM OR RELATED TO THE SERVICE SHALL NOT 
            EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">8. Account Termination</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            You may terminate your account at any time by contacting us or through the account settings. 
            Termination will take effect immediately, and you will lose access to the Service and any 
            generated content.
          </p>
          <p>
            We reserve the right to suspend or terminate your account at any time, with or without cause, 
            at our sole discretion. We may also terminate or suspend access immediately, without prior 
            notice, for any conduct that we believe violates these Terms or is harmful to other users, 
            us, or third parties.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">9. Privacy and Data</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            Your privacy is important to us. Please review our <a href="/legal/privacy" className="text-[#FFFFFF] underline hover:text-[#999999]">Privacy Policy</a> to understand how we collect, 
            use, and protect your personal information.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">10. Modifications to Terms</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            We reserve the right to modify these Terms at any time. We will notify users of significant 
            changes via email and update the "Last updated" date at the top of this page. Your continued 
            use of the Service after such modifications constitutes your acceptance of the updated Terms.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">11. Governing Law</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            These Terms shall be governed by and construed in accordance with applicable laws, without 
            regard to its conflict of law provisions. Any disputes arising from these Terms or your use 
            of the Service shall be resolved through binding arbitration or in the courts of the 
            applicable jurisdiction.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4 text-[#FFFFFF]">12. Contact Information</h2>
        <div className="text-[#CCCCCC] space-y-4">
          <p>
            If you have any questions about these Terms of Service, please contact us at:
          </p>
          <p className="bg-[#191919] p-4 rounded-lg">
            <strong className="text-[#FFFFFF]">DeepMark</strong><br />
            Email: legal@deepmark.ai<br />
            Website: deepmark.ai
          </p>
        </div>
      </section>
    </article>
  );
}
